apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pointlify-com-tls
spec:
  secretName: pointlify-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pointlify.com
  dnsNames:
    - pointlify.com
    - www.pointlify.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - pointlify.com
          - www.pointlify.com
